### ISSUE TITLE
docarray proto module cant be imported by child Processes

### ISSUE THREAD

**Issue by Jackmin801** [docarray/docarray#1071]
**Describe the bug**
docarray proto module cant be imported my child Processes

**To Reproduce**
script.py
```python
import torch
import multiprocessing as mp
from docarray import DocumentArray, BaseDocument
from docarray.typing import TorchTensor

class Meow(BaseDocument):
    tensor: TorchTensor

def deserialize(pb_msg):
    return DocumentArray[Meow].from_protobuf(pb_msg)

with mp.Pool(2) as p:
    a = p.map(deserialize, [DocumentArray[Meow]([Meow(tensor=torch.randn(x)) for x in range(4)]).to_protobuf() for _ in range(2)])
    print(a)
```
Output
```console
Traceback (most recent call last):
  File "dragon.py", line 13, in <module>
    a = p.map(deserialize, [DocumentArray[Meow]([Meow(tensor=torch.randn(x)) for x in range(4)]).to_protobuf() for _ in range(2)])
  File "/home/jackmin/miniconda3/envs/docarray/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/jackmin/miniconda3/envs/docarray/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/jackmin/miniconda3/envs/docarray/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/jackmin/miniconda3/envs/docarray/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/jackmin/miniconda3/envs/docarray/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'docarray_pb2.DocumentArrayProto'>: import of module 'docarray_pb2' failed
```

**Expected behavior**
No error

**Comment by JoanFM** [comment]
This is expected, as per any Protobuf object https://groups.google.com/g/protobuf/c/VqWJ3BmQXVg

Happens the same in v1
