### ISSUE TITLE
DocumentArray is not Generic for TypeVar

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1146]
# Context

DocumentArray is a Generic but cannot be used with TypeVar. We need to handle this case as well. We need to modify the `class_getitem` of `AnyDocumentArray`.

This don't work
```python
from docarray import DocumentArray, BaseDocument
from typing import TypeVar, List

T = TypeVar('T', bound=BaseDocument)


def f(a: DocumentArray[T]) -> DocumentArray[T]:
    return a

```

```bash
Traceback (most recent call last):
  File "scratch_3.py", line 7, in <module>
    def f(a: DocumentArray[T]) -> DocumentArray[T]:
  File "docarray/docarray/array/abstract_array.py", line 38, in __class_getitem__
    if not issubclass(item, BaseDocument):
  File "/versions/3.9.10/lib/python3.9/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

whereas this work fine
```python

def g(a: List[T]) -> List[T]:
    return a
```

**Comment by agaraman0** [comment]
Hey @samsja  i would like to pick this up.

**Comment by samsja** [comment]
Hey @agaraman0 unfortunately the PR to fix this bug has already been merged: https://github.com/docarray/docarray/pull/1147

I will close this issue
