### ISSUE TITLE
`annlite`  document store delete element bug

### ISSUE THREAD

**Issue by beidongjiedeguang** [docarray/docarray#1150]
**Describe the bug**
Cannot add a member with the same id after deleting the member.

**To Reproduce**

```python
from docarray import Document, DocumentArray

da = DocumentArray(storage='annlite', config={'n_dim': 10})

with da:
    da.extend([Document(id=i) for i in '123'])
    del da['1']
    da.extend([Document(id=i) for i in '1']) # Error encountered
```

**Output**
```shell
$ python issue.py
1 0 0
Deleted 1 at: 2023-02-21 01:58:45.078295
Traceback (most recent call last):
  File "issue.py", line 9, in <module>
    da.extend([Document(id=i) for i in '1'])
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/docarray/array/storage/base/seqlike.py", line 81, in extend
    self._extend(values, **kwargs)
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/docarray/array/storage/annlite/seqlike.py", line 19, in _extend
    self._annlite.index(docs)
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/annlite/index.py", line 295, in index
    return super(AnnLite, self).insert(x, assigned_cells, docs)
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/annlite/container.py", line 279, in insert
    offsets = self.cell_table(cell_id).insert(docs)
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/annlite/storage/table.py", line 255, in insert
    cursor.execute(sql, values[-1])
sqlite3.IntegrityError: UNIQUE constraint failed: table_0._doc_id
```

**OS** 
WSL(ubuntu22.04) in win11

**Comment by jemmyshin** [comment]
This is a bug in `annlite`, we have fixed it and you can try it again via `pip install annlite==0.5.7`

**Comment by beidongjiedeguang** [comment]
> This is a bug in `annlite`, we have fixed it and you can try it again via `pip install annlite==0.5.7`

@jemmyshin  Thank you for fixing the bug so promptly. The above issues have indeed been well addressed in version `annlite==0.5.7`.
In the meantime, I have found a new bug:  when using the 'data_path' parameter, there is an error when deleting a member of a DocumentArray by id.

**To Reproduce**  

Firstly, adding two members to the DocumentArray will automatically store the contents in the `./test_annlite` directory during runtime:
```python
from docarray import Document, DocumentArray

store = 'annlite'
da = DocumentArray(storage=store,
                   config={'n_dim': 10, 'data_path': './test_annlite'})
with da:
    da.extend([Document(id=i) for i in '12'])
```
Then, delete the member corresponding to id = '1' :
```python
from docarray import Document, DocumentArray

store = 'annlite'
da = DocumentArray(storage=store,
                   config={'n_dim': 10, 'data_path': './test_annlite'})
with da:
    del da['1']
```
output:  
```shell
2023-02-25 23:02:09.123 | INFO     | annlite.index:restore:670 - restore Annlite from local
2023-02-25 23:02:09.124 | INFO     | annlite.index:_rebuild_index_from_local:777 - Rebuild the indexer from scratch
2023-02-25 23:02:09.124 | INFO     | annlite.index:_rebuild_index_from_local:794 - Load the model from test_annlite/parameters-28ec7aafb15c03d2f2ee5c69a160d8be
1 0 0
Deleted 1 at: 2023-02-25 15:02:09.151971
```
It looks like everything is working fine.  
Next, delete the other member by id='2' : 
```python
from docarray import Document, DocumentArray

store = 'annlite'
da = DocumentArray(storage=store,
                   config={'n_dim': 10, 'data_path': './test_annlite'})
with da:
    del da['2'] # Error encountered
```
**Output**  
```shell
2 0 1
Traceback (most recent call last):
  File "issue.py", line 7, in <module>
    del da['2']
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/docarray/array/mixins/delitem.py", line 31, in __delitem__
    self._del_doc(index)
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/docarray/array/storage/base/getsetdel.py", line 107, in _del_doc
    self._del_doc_by_id(_id)
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/docarray/array/storage/annlite/getsetdel.py", line 32, in _del_doc_by_id
    self._del_docs_by_ids([_id])
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/docarray/array/storage/annlite/getsetdel.py", line 43, in _del_docs_by_ids
    self._annlite.delete(ids)
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/annlite/index.py", line 535, in delete
    super().delete(
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/annlite/container.py", line 397, in delete
    self.vec_index(cell_id).delete([offset])
  File "/home/kunyuan/miniconda3/envs/torch/lib/python3.8/site-packages/annlite/core/index/hnsw/index.py", line 171, in delete
    self._index.mark_deleted(i)
RuntimeError: Label not found
```
As shown in the output, a RuntimeError was thrown at this step.

**Comment by JoanFM** [comment]
Hey @beidongjiedeguang ,

If u have a new buf, could u please close this ticket and open a new one?

**Comment by beidongjiedeguang** [comment]
> Hey @beidongjiedeguang ,
> 
> If u have a new buf, could u please close this ticket and open a new one?

Okay, very willing

**Comment by beidongjiedeguang** [comment]
Relate to #1178
