### ISSUE TITLE
bug: torch 2.x with `TorchTensor`

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1269]
PyTorch 2.0 adds extensive compilation support to the framework; we should test this with our `TorchTensor` implementations and make sure that
1) it works
2) we don't somehow negate the performance gains

**Comment by h4shk4t** [comment]
Hi! I'd like to work on this issue

**Comment by JohannesMessner** [comment]
> Hi! I'd like to work on this issue
> 
> 

Sure thing! I just discovered that I cannot formally assign it to you bc I am on mobile, but consider it yours!

**Comment by JohannesMessner** [comment]
Hi @h4shk4t , have you had time to look into this?

**Comment by JohannesMessner** [comment]
Issue back open for whoever wants to take it ^^

**Comment by JohannesMessner** [comment]
So I gave this a try, and sadly it doesn't work:

```python
import torch
from docarray.typing import TorchTensor
from pydantic import parse_obj_as


def fn(a, b):
    return a @ b


# native
a, b = torch.rand(1000, 1000), torch.rand(1000, 1000)
fn_c = torch.compile(fn)
fn_c(a, b)
print('native successful')

# docarray
a, b = parse_obj_as(TorchTensor[1000, 1000], torch.rand(1000, 1000)), parse_obj_as(TorchTensor[1000, 1000], torch.rand(1000, 1000))
fn_c = torch.compile(fn)
fn_c(a, b)
print('docarray successful')
```
```bash
native successful
Traceback (most recent call last):
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 299, in transform
    tracer = InstructionTranslator(
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1670, in __init__
    self.symbolic_locals = collections.OrderedDict(
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1673, in <genexpr>
    VariableBuilder(
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 172, in __call__
    return self._wrap(value).clone(**self.options())
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 453, in _wrap
    istype(value, (type, types.FunctionType))
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 346, in istype
    return type(obj) in allowed_types
  File "/home/johannes/Documents/jina/docarrayv2/docarray/typing/tensor/abstract_tensor.py", line 101, in __eq__
    if cls._equals_special_case(other):
  File "/home/johannes/Documents/jina/docarrayv2/docarray/typing/tensor/abstract_tensor.py", line 62, in _equals_special_case
    is_tensor = is_type and AbstractTensor in other.mro()
TypeError: descriptor 'mro' of 'type' object needs an argument

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/johannes/.config/JetBrains/PyCharmCE2023.2/scratches/scratch_182.py", line 18, in <module>
    fn_c(a, b)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/johannes/Documents/jina/docarrayv2/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 394, in _compile
    raise InternalTorchDynamoError() from e
torch._dynamo.exc.InternalTorchDynamoError

Process finished with exit code 1
```
Seems fixable at first glance, I'll work on it
