### ISSUE TITLE
Bug: cannot stack empty torch tensor

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#1425]
How to reproduce:
```python
from docarray import BaseDoc, DocVec
from docarray.typing import TorchTensor
class MyDoc(BaseDoc):
    tens: Optional[TorchTensor]
    
vec = DocVec[MyDoc]([MyDoc(), MyDoc()])
```
```bash
Traceback (most recent call last):
  File "/home/johannes/.cache/pypoetry/virtualenvs/docarray-EljsZLuq-py3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-e510c10fcd92>", line 1, in <cell line: 1>
    vec = DocVec[MyDoc]([MyDoc(), MyDoc()])
  File "/home/johannes/Documents/jina/docarrayv2/docarray/array/doc_vec/doc_vec.py", line 160, in __init__
    cast(AbstractTensor, tensor_columns[field_name])[i] = val
```

**Comment by JohannesMessner** [comment]
oooops, user error, this works:
```python
vec = DocVec[MyDoc]([MyDoc(), MyDoc()], tensor_type=TorchTensor)
```
