### ISSUE TITLE
json method not working correctly with DocVec

### ISSUE THREAD

**Issue by movchan74** [docarray/docarray#1490]
#### Description:
The `json` method doesn't work correctly when using `DocVec`. The `json` output for a field containing a `DocVec` instance returns `null`.

#### Steps to reproduce:

Using the following code with a custom class and `DocList`:

```python
from docarray import DocVec, BaseDoc, DocList
from docarray.documents.image import ImageDoc

class CustomClass(BaseDoc):
    images: DocList[ImageDoc]
        
images = DocList[ImageDoc]([ImageDoc(url=f'http://url.com/{i}.png') for i in range(10)])
custom_instance = CustomClass(images=images)
custom_instance.json()
```

Output:

```
'{"id":"05094c8c7045d988c58791da43f79584","images":[{"id":"c7cb6d04ddda6d5f6299959fcae6241a","url":"http://url.com/0.png","tensor":null,"embedding":null,"bytes_":null},{"id":"1175d1988e1173b5217dd148dca705f7","url":"http://url.com/1.png","tensor":null,"embedding":null,"bytes_":null},{...}]}' 
```

Using the following code with a custom class and `DocVec`:

```python
from docarray import DocVec, BaseDoc, DocList
from docarray.documents.image import ImageDoc

class CustomClass(BaseDoc):
    images: DocVec[ImageDoc]
        
images = DocVec[ImageDoc]([ImageDoc(url=f'http://url.com/{i}.png') for i in range(10)])
custom_instance = CustomClass(images=images)
custom_instance.json()
```

Output:

```
'{"id":"2f040340fa6ad9dbc10d394609251afa","images":null}'
```

#### Expected behavior:

The `json` method should return the correct output when using `DocVec` with any custom class, similar to how it works with `DocList`.

**Comment by JoanFM** [comment]
Note: 

on `main`, the first part raises a ValueError:

```python
Traceback (most recent call last):
  File "aux.py", line 9, in <module>
    print(custom_instance.json())
  File "/home/joan/jina/docarray/docarray/base_doc/doc.py", line 221, in json
    **dumps_kwargs,
  File "pydantic/main.py", line 492, in pydantic.main.BaseModel.json
  File "pydantic/main.py", line 868, in _iter
  File "pydantic/main.py", line 794, in pydantic.main.BaseModel._get_value
  File "/home/joan/jina/docarray/docarray/array/doc_list/doc_list.py", line 120, in __init__
    super().__init__(docs)
  File "/home/joan/jina/docarray/docarray/array/doc_list/doc_list.py", line 148, in _validate_docs
    yield self._validate_one_doc(doc)
  File "/home/joan/jina/docarray/docarray/array/doc_list/doc_list.py", line 153, in _validate_one_doc
    raise ValueError(f'{doc} is not a {self.doc_type}')
ValueError: {'id': '08ddfb573dff754baee479e1b3a894b6', 'url': ImageUrl('http://url.com/0.png', host_type='domain'), 'tensor': None, 'embedding': None, 'bytes_': None} is not a <class 'docarray.documents.image.ImageDoc'>
```

**Comment by samsja** [comment]
Hey @movchan74 so far we don't support `to_json` on DocVec which is why the nested DocVec cannot be serialized with json. Once we support `to_json` on DocVec we will make sure that the nested support is working and therefore fix the bug that you see.

**Comment by JoanFM** [comment]
Closing in favor of #1330
