### ISSUE TITLE
No Dimensionality Specified for using Field 

### ISSUE THREAD

**Issue by Robbie-Palmer** [docarray/docarray#1609]
The documentation for the DocIndex - Vector Search Introduction gives example code which uses a predefined Document as a schema, where the embedding is specified as a `pydantic` `Field` with an `n_dim` property set
The data is indexed and queried using [HnswDocumentIndex](https://docs.docarray.org/API_reference/doc_index/backends/hnswlib/#docarray.index.backends.hnswlib.HnswDocumentIndex)

The example code as one script looks like:
```python
import logging

import numpy as np
from docarray import DocList
from docarray.documents import TextDoc
from docarray.index import HnswDocumentIndex
from docarray.typing import AnyTensor
from pydantic import Field

logging.getLogger('docarray').setLevel(logging.INFO)


class MyDoc(TextDoc):
    embedding: AnyTensor = Field(n_dim=128)


db = HnswDocumentIndex[MyDoc](work_dir='test_db3')
docs = DocList[MyDoc]([MyDoc(embedding=np.random.rand(128), text=f'text {i}') for i in range(100)])
db.index(docs)

query = MyDoc(embedding=np.random.rand(128), text='query')
matches, scores = db.find(query, search_field='embedding', limit=5)
print(f'{matches=}')
print(f'{matches.text=}')
print(f'{scores=}')
```

The `embedding` field isn't found during querying, and by looking at the logs, we can see it wasn't indexed because
> docarray - Not indexing column embedding; either `index=False` is set or no dimensionality is specified

Full output:
```
INFO - docarray - DB config created
INFO - docarray - Runtime config created
INFO - docarray - Not indexing column embedding; either `index=False` is set or no dimensionality is specified
INFO - docarray - Connection to DB has been established
INFO - docarray - HnswDocumentIndex[MyDoc] has been initialized
Traceback (most recent call last):
  File "/home/robbie/repos/search/search/__init__.py", line 22, in <module>
    matches, scores = db.find(query, search_field='embedding', limit=5)
  File "/home/robbie/miniconda3/envs/search/lib/python3.10/site-packages/docarray/index/abstract.py", line 466, in find
    docs, scores = self._find(
  File "/home/robbie/miniconda3/envs/search/lib/python3.10/site-packages/docarray/index/backends/hnswlib.py", line 304, in _find
    docs, scores = self._find_batched(
  File "/home/robbie/miniconda3/envs/search/lib/python3.10/site-packages/docarray/index/backends/hnswlib.py", line 287, in _find_batched
    index = self._hnsw_indices[search_field]
KeyError: 'embedding'
```

If the field in the Document is redefined as `embedding: NdArray[128]` (an alternative option listed in the documentation) then this runs correctly

**Comment by JoanFM** [comment]
Hey @Robbie-Palmer ,

it seems that it should be `dim` and not `n_dim`. I will check the Documentation

**Comment by JoanFM** [comment]
This is specific for `HNSWLib` the right configuration is `dim` and not `n_dim`
