### ISSUE TITLE
Weaviate hybrid example errors: init missing required positional argument 'properties'

### ISSUE THREAD

**Issue by Robbie-Palmer** [docarray/docarray#1612]
The documentation on the Weaviate Document Index, [gives code for executing a hybrid search](https://docs.docarray.org/user_guide/storing/index_weaviate/)

The example code as one script looks like:
```python
import numpy as np
from docarray import BaseDoc
from docarray.index.backends.weaviate import WeaviateDocumentIndex
from docarray.typing import NdArray
from pydantic import Field


class Document(BaseDoc):
    text: str
    embedding: NdArray[2] = Field(dims=2, is_embedding=True)
    file: NdArray[100] = Field(dims=100)


batch_config = dict(batch_size=20, dynamic=False, timeout_retries=3, num_workers=1)
runtime_config = WeaviateDocumentIndex.RuntimeConfig(batch_config=batch_config)

db_config = WeaviateDocumentIndex.DBConfig(host="http://localhost:8080")
store = WeaviateDocumentIndex[Document](db_config=db_config)
store.configure(runtime_config)

docs = [
    Document(text="Hello world", embedding=np.array([1, 2]), file=np.random.rand(100), id="1"),
    Document(text="Hello world, how are you?", embedding=np.array([3, 4]), file=np.random.rand(100), id="2"),
    Document(text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
             embedding=np.array([5, 6]), file=np.random.rand(100), id="3", ),
]
store.index(docs)

hybrid_search = store.build_query().text_search("world").find([1, 2]).limit(2).build()
hybrid_search_result = store.execute_query(hybrid_search)
print(hybrid_search_result.text)
```

But this throws the error:
```
Traceback (most recent call last):
  File "/home/robbie/repos/search/search/__init__.py", line 29, in <module>
    hybrid_search = store.build_query().text_search("world").find([1, 2]).limit(2).build()
  File "/home/robbie/miniconda3/envs/search/lib/python3.10/site-packages/docarray/index/backends/weaviate.py", line 780, in build
    self._make_proper_hybrid_query(q)
  File "/home/robbie/miniconda3/envs/search/lib/python3.10/site-packages/docarray/index/backends/weaviate.py", line 806, in _make_proper_hybrid_query
    hybrid_query = weaviate.gql.get.Hybrid(
TypeError: Hybrid.__init__() missing 1 required positional argument: 'properties'
```

This appears to be related to [this comment](https://github.com/docarray/docarray/issues/1504#issuecomment-1539790603) on another issue

**Comment by hsm207** [comment]
@Robbie-Palmer which version of the weaviate server and client are you using?

**Comment by Robbie-Palmer** [comment]
I ran `pip install docarray[weaviate]` which installed v3.19.2 of the client
I'm running the server via Docker-compose with image `semitechnologies/weaviate:1.19.6`

**Comment by samsja** [comment]
@hsm207 any idea where the problem is coming from ?

**Comment by hsm207** [comment]
@samsja it is coming from a recent update to the weaviate python client to allow [search by specific fields(s)](https://weaviate.io/developers/weaviate/search/hybrid#selected-properties-only) by the bm25 portion of the hybrid search.

**Comment by JoanFM** [comment]
@hsm207 , can we then please update?
