### ISSUE TITLE
HNSWLib Indexer cannot knn query in subindex

### ISSUE THREAD

**Issue by oytuntez** [docarray/docarray#1866]
### Initial Checks

- [X] I have read and followed [the docs](https://docs.docarray.org/) and still think this is a bug

### Description

Searching vectors in subindex fails in HNSWLib index store:

```bash
Traceback (most recent call last):
  File "/Users/oytuntez/motaword/jina-documents/clip-deploy.py", line 72, in <module>
    di.find_subindex(td, 'texts', 'embedding', 1)
  File "/Users/oytuntez/motaword/docarray/docarray/index/abstract.py", line 532, in find_subindex
    sub_docs, scores = self._find_subdocs(
  File "/Users/oytuntez/motaword/docarray/docarray/index/abstract.py", line 1189, in _find_subdocs
    return self._subindices[fields[0]].find(
  File "/Users/oytuntez/motaword/docarray/docarray/index/abstract.py", line 503, in find
    docs, scores = self._find(
  File "/Users/oytuntez/motaword/docarray/docarray/index/backends/hnswlib.py", line 332, in _find
    docs, scores = self._find_batched(
  File "/Users/oytuntez/motaword/docarray/docarray/index/backends/hnswlib.py", line 324, in _find_batched
    return self._search_and_filter(
  File "/Users/oytuntez/motaword/docarray/docarray/index/backends/hnswlib.py", line 690, in _search_and_filter
    result_das = [
  File "/Users/oytuntez/motaword/docarray/docarray/index/backends/hnswlib.py", line 691, in <listcomp>
    self._get_docs_sqlite_hashed_id(
  File "/Users/oytuntez/motaword/docarray/docarray/index/backends/hnswlib.py", line 555, in _get_docs_sqlite_hashed_id
    docs_unsorted = self._get_docs_sqlite_unsorted(hashed_ids)
  File "/Users/oytuntez/motaword/docarray/docarray/index/backends/hnswlib.py", line 541, in _get_docs_sqlite_unsorted
    docs.append(self._doc_from_bytes(data_bytes, reconstruct_embeddings, out))
  File "/Users/oytuntez/motaword/docarray/docarray/index/backends/hnswlib.py", line 596, in _doc_from_bytes
    schema_cls._get_field_annotation(k)
AttributeError: 'NoneType' object has no attribute '_to_node_protobuf'
```

Here is the case to replicate the issue:
```python

import numpy as np
import os
from docarray.index import HnswDocumentIndex

os.environ['JINA_LOG_LEVEL'] = 'DEBUG'
from docarray import DocList, BaseDoc
from docarray.documents.text import TextDoc
from docarray.documents.image import ImageDoc


class QuoteFile(BaseDoc):
    quote_file_id: int = None
    texts: DocList[TextDoc] = None
    images: DocList[ImageDoc] = None


class SearchResult(BaseDoc):
    results: DocList[QuoteFile] = None


hnsw_config_quote_files = HnswDocumentIndex.DBConfig(index_name='quote_files', work_dir=os.path.abspath('./.cache'), default_column_config={
        np.ndarray: {
            'dim': 512,
            'index': True,
            'space': 'l2',  # 'l2', 'ip', 'cosine'
            'max_elements': 50000,
            'ef_construction': 200,
            'ef': 100,
            'M': 16,
            'allow_replace_deleted': True,
            'num_threads': 1,
        },
        'TEXT': {},
        'INTEGER': {},
        None: {},
    },)

di = HnswDocumentIndex[QuoteFile](hnsw_config_quote_files)

td = TextDoc(text="Hello World")
td.id = "test-text"
td.embedding = np.zeros(512)

qf = QuoteFile()
qf.id = "test"
qf.quote_file_id = 109
qf.texts = DocList[TextDoc]([td])

di.index(qf)

sqf = QuoteFile()
sqf.id = "test"
sqff = di.filter({'quote_file_id': {'$eq': 109}})
print(sqff[0].summary())


td = TextDoc(text="Hello World")
td.id = "test-text"
td.embedding = np.zeros(512)
di.find_subindex(td, 'texts', 'embedding', 1)
```

### Python, DocArray & OS Version

```Text
jina==3.23.2
docarray=latest and our minor fork at motaword/docarray
```

### Affected Components

- [X] [Vector Database / Index](https://docs.docarray.org/user_guide/storing/docindex/)
- [ ] [Representing](https://docs.docarray.org/user_guide/representing/first_step)
- [ ] [Sending](https://docs.docarray.org/user_guide/sending/first_step/)
- [ ] [storing](https://docs.docarray.org/user_guide/storing/first_step/)
- [X] [multi modal data type](https://docs.docarray.org/data_types/first_steps/)

**Comment by JoanFM** [comment]
Is there any relevant change in the fork that one may need to be aware of?

**Comment by oytuntez** [comment]
I don't think so, it's mostly about optional fields, here is a diff: https://github.com/docarray/docarray/compare/main...MotaWord:docarray:hotfix/optional-leaf-object

**Comment by JoanFM** [comment]
What is the Pydantic version u are using?

**Comment by JoanFM** [comment]
If you apply the recommendation in ES section:

```Using a predefined document as schema
DocArray offers a number of predefined documents, like [ImageDoc](https://docs.docarray.org/API_reference/documents/documents/#docarray.documents.ImageDoc) and [TextDoc](https://docs.docarray.org/API_reference/documents/documents/#docarray.documents.TextDoc). If you try to use these directly as a schema for a Document Index, you will get unexpected behavior: Depending on the backend, an exception will be raised, or no vector index for ANN lookup will be built.

The reason for this is that predefined documents don't hold information about the dimensionality of their .embedding field. But this is crucial information for any vector database to work properly!

You can work around this problem by subclassing the predefined document and adding the dimensionality information:


Using type hint
Using Field()

from docarray.documents import TextDoc
from docarray.typing import NdArray
from docarray.index import ElasticDocIndex


class MyDoc(TextDoc):
    embedding: NdArray[128]


db = ElasticDocIndex[MyDoc](index_name='test_db')

Once you have defined the schema of your Document Index in this way, the data that you index can be either the predefined Document type or your custom Document type.

The [next section](https://docs.docarray.org/user_guide/storing/index_elastic/#index) goes into more detail about data indexing, but note that if you have some TextDocs, ImageDocs etc. that you want to index, you don't need to cast them to MyDoc:


from docarray import DocList

# data of type TextDoc
data = DocList[TextDoc](
    [
        TextDoc(text='hello world', embedding=np.random.rand(128)),
        TextDoc(text='hello world', embedding=np.random.rand(128)),
        TextDoc(text='hello world', embedding=np.random.rand(128)),
    ]
)

# you can index this into Document Index of type MyDoc
db.index(data)
```
The solution works, 

```python
import os
import numpy as np
from docarray.index import HnswDocumentIndex
from typing import Optional
from docarray import DocList, BaseDoc
from docarray.documents.text import TextDoc
from docarray.typing import NdArray


class MyTextDoc(TextDoc):
    embedding: Optional[NdArray[512]] = None

class QuoteFile(BaseDoc):
    quote_file_id: int = None
    texts: DocList[MyTextDoc] = None


class SearchResult(BaseDoc):
    results: DocList[QuoteFile] = None


hnsw_config_quote_files = HnswDocumentIndex.DBConfig(index_name='quote_files', work_dir=os.path.abspath('./.cache'), default_column_config={
        np.ndarray: {
            'dim': 512,
            'index': True,
            'space': 'l2',  # 'l2', 'ip', 'cosine'
            'max_elements': 50000,
            'ef_construction': 200,
            'ef': 100,
            'M': 16,
            'allow_replace_deleted': True,
            'num_threads': 1,
        },
        'TEXT': {},
        'INTEGER': {},
        None: {},
    },)

di = HnswDocumentIndex[QuoteFile](hnsw_config_quote_files)

td = TextDoc(text="Hello World")
td.id = "test-text"
td.embedding = np.zeros(512)

qf = QuoteFile()
qf.id = "test"
qf.quote_file_id = 109
qf.texts = DocList[TextDoc]([td])

di.index(qf)

sqf = QuoteFile()
sqf.id = "test"
sqff = di.filter({'quote_file_id': {'$eq': 109}})
print(sqff[0].summary())


td = MyTextDoc(text="Hello World")
td.id = "test-text"
td.embedding = np.zeros(512)
di.find_subindex(td, 'texts', 'embedding', 1)
```

What I will do is move this Documentation to a part common for all the Indexes.

**Comment by oytuntez** [comment]
Testing right away.

**Comment by JoanFM** [comment]
@JohannesMessner and @samsja may have more clarity on these limitations

**Comment by oytuntez** [comment]
Worked! Thank you, closing this one.

**Comment by samsja** [comment]
> Worked! Thank you, closing this one.

great !
