### ISSUE TITLE
bug(v2): local file paths do not support ../

### ISSUE THREAD

**Issue by JohannesMessner** [docarray/docarray#980]

**Comment by Jake-00** [comment]
hi @JohannesMessner
IMO, supporting the relative path with symbol `..` or `.` only relates to file url belonging to local file system. To avoid Pydantic's error, we could parse file url in `Image` module to convert relative path to absolute path. How about this solution?

**Comment by JoanFM** [comment]
Hey @Jake-00 , I believe this would be a nice solution. Would you like to provide a PR fixing this behavior?

**Comment by Jake-00** [comment]
sure

**Comment by Jake-00** [comment]
Sure

**Comment by Jake-00** [comment]
> How to reproduce:
> 
> from docarray import Image import os
> 
> ```python
> from docarray import Image
> 
> url = 'file://../../../../Documents/jina/docarrayv2/tests/toydata/image-data/05978.jpg'
> img = Image(url=url)
> ```
> 
> ```
> Traceback (most recent call last):
>   File "/home/johannes/.config/JetBrains/PyCharmCE2022.3/scratches/scratch_116.py", line 9, in <module>
>     img = Image(url=url)
>   File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Image
> url
>   URL host invalid (type=value_error.url.host)
> ```
> 
> Pydantic only supports file _urls_, not file _paths_, so `..` is no supported. We need to enable this for our use cases.

`from docarray.document import Image`  is the right module path for importing, instead of `from docarray import Image` .

**Comment by JohannesMessner** [comment]
Hi @Jake-00!

I also like the idea of converting to an absolute path, but do you think it could be done in our `AnyUrl` (this might be a bit tricky because of the tight coupling with pydantic's `AnyUrl`), or alternatively in BaseDocument (this might be a bit tricky because all the subclasses of `AnyUrl` would have to be handled at once)?
I think that would be better than doing it in `Image` because the fix should work for all urls, not just `ImageUrl`, and for all Documents (even user defined ones), not just `Image`.
So finding a place where we can hit all of those cases at once would be the best!

(I have a small concern about the converting to absolute path approach, which is the following: say I want to send a local file path in a Document to a server, which I also control, and I want to specify a file on the server using a relative path. Then that relative path would be converted to absolute path on the client machine, which will not be the same absolute path as on the server machine. But this is probably not a good pattern anyways, so I would say it is fine)

> from docarray.document import Image is the right module path for importing, instead of from docarray import Image 

Yeah good catch, we changed the package structure after this ticket was written :)

**Comment by JohannesMessner** [comment]
Hi @Jake-00, do you still plan to work on this? Otherwise we might assign this ticket to someone else

**Comment by Jake-00** [comment]
I just have been occupied in other things, feel free to reassign other person. And sorry for the late response.
